### ISSUE TITLE
PathSettings exception error

### ISSUE THREAD

**Issue by joeblakey17** [greyshirtguy/Pro7ChordEditorWin#1]
** Which version of PRo7ChordEditor are you using**
See version # in Window Title.
0.941

**Describe the bug**
At launch, i get a dialogue box that says:
Exception Could not find file
'C:\Users\joebl\AppData\Roaming\RenewedVision\ProPresenter\PathSettings.ProPaths'. while trying to read PathSettings.ProPaths

**To Reproduce**
1. Double-click application
2. See error
3. Application opens after clicking OK but no presentations are available to select

**Expected behavior**
A clear and concise description of what you expected to happen
Application opens and populates presentations that I can edit

**Screenshots**
If applicable, add screenshots (desktop video recording) to help explain your problem.

**Exact version of Pro7 used:**
ProPresenter -> About
7.11 (118161426)

**Desktop (please complete the following information):**
 Run "Winver" and report version of Windows you are using.
Version 22H2 (OS Build 22621.1105)

** Log file & Additional context**
Please attach the `Pro7ChordEditor.log` file that was created in the application folder.
Ideally, attach the .pro document you are tyring to edit
[Pro7ChordEditor.log](https://github.com/greyshirtguy/Pro7ChordEditorWin/files/10484538/Pro7ChordEditor.log)

**Comment by greyshirtguy** [comment]
....AppData\Roaming\RenewedVision\ProPresenter\PathSettings.ProPaths is a file that contains configuration for the install of Pro7....
That file is not found on the system you are running the Pro7ChordEditor...
Is Pro7 installed on that computer? _It looks like it's not installed_

The current version of the app is hard-coded to automatically show your Pro7 libraries by looking at this config...
_Thought:_ I could update it to not need Pro7 installed and just let you manually select a folder of *.pro docs I suppose...

**Comment by greyshirtguy** [comment]
....rushing answers here today (while at work) ...If anything I say does not make sense-  please feel free to ask again!

**Comment by joeblakey17** [comment]
Pro7 is installed on this computer. I looked for the Pathsettings.ProPaths file and it doesn't exist anywhere on my PC. I just updated Pro7 to see if that file would be included in the latest version and it wasn't. Thanks for your help!

**Comment by greyshirtguy** [comment]
Hmmm.... I've obviously missed a use-case for other locations that file could be stored for Pro7 installs....
I don't know off hand...and will take a look at my Windows PC when I get home from work tonight....

Until then, I would _guess_ that perhaps it is stored elsewhere when Pro7 is either:
* Installed by a different user than "joebl"
* Installed for all users (perhaps in C:\programdata
* Some other completly different explanation...

I'll know more tonight and comment further soon

**Comment by greyshirtguy** [comment]
Okay - I think I've figured out my mistake...
I assumed that file is always there - but I think it's only created if you customise the "Support Files" preference... otherwise the app probablhy assumes a default of %USERPROFILE%\Documents....
I'll try and confirm this - but either way, I'll make an update that works soon!

**Comment by greyshirtguy** [comment]
Fixed in [Release 0.942](https://github.com/greyshirtguy/Pro7ChordEditorWin/releases/tag/0.942)

**Comment by joeblakey17** [comment]
I was able to open my library! Thanks for the fix!

**Comment by greyshirtguy** [comment]
Great! Don't forget to have lots of backups of your library before (and during) messing with it!
